package com.imajuk.display{    import flash.display.FrameLabel;
    import flash.utils.getTimer;
    import flash.display.MovieClip;    import fl.motion.easing.Linear;
    import org.libspark.thread.Thread;    /**     * @author shinyamaharu     */    public class MovieClipReverseThread extends Thread     {        private var mc : MovieClip;
        private var duration : Number;
        private var easing : Function;
        private var time : Number = 0;
        private var begin : int;        private var end : int;        private var st : int = -1;        private var enterframeCallback : Function;
        public function MovieClipReverseThread(                            mc : MovieClip,                             reverse : Boolean = false,                             duration : Number = 1,                             easing : Function = null,                            begin : * = 1,                            end : * = null,                            enterframeCallback:Function = null                        )        {            super();            this.mc = mc;            this.duration = duration;            this.easing = easing == null ? Linear.easeNone : easing;            this.enterframeCallback = enterframeCallback;                        var labels:Array = mc.currentLabels;            if ((typeof begin) == "number")                this.begin = begin;            else if ((typeof begin) == "string")                this.begin = getFrameIndexFromLabel(labels, begin, 1);            if ((typeof end) == "number")                this.end = end;            else if ((typeof end) == "string")                this.end   = getFrameIndexFromLabel(labels, end, mc.totalFrames);                        if (reverse)            {                var temp : int = this.begin;                this.begin = this.end;                this.end = temp;            }//            trace('this.begin: ' + (this.begin));//            trace('this.end: ' + (this.end));        }        private function getFrameIndexFromLabel(labels:Array, name:String, defaultIndex:int = 0) : int         {        	var a:Array = labels.filter(function(f:FrameLabel, ...param):Boolean            {                return f.name == name;            });            if (a.length > 1)                throw new Error("MovieClip[" + mc.name + "]に" + name + "という名前のラベルが複数存在します.");            if (a.length == 1)                return FrameLabel(a[0]).frame;            return defaultIndex;
        }
        override protected function run() : void        {            if(isInterrupted)        	   return;        	           	if (end == mc.currentFrame)        	   return;        	               next(run);                        if (st == -1)            {                st = getTimer();                time = 0;            }            else            {                time = (getTimer() - st) * 0.001;            }            var frm : int = Math.round(easing(time, begin, end - begin, duration));            mc.gotoAndStop(frm);                        if (enterframeCallback != null)                enterframeCallback();                        if (time >= duration)                interrupt();        }        override protected function finalize() : void        {        }    }}