package com.imajuk.geom {
    import flash.geom.Point;    /**
     * @author yamaharu     * flash.geom.PointをIGeomの実装クラスとして振る舞わせるAdapter
     */
    public class Point2D implements IGeom     {        //--------------------------------------------------------------------------        //        //  Constructor        //        //--------------------------------------------------------------------------        public function Point2D(x:Number = 0, y:Number = 0)        {            _p = new Point(x, y);        }        //--------------------------------------------------------------------------        //        //  Variables        //        //--------------------------------------------------------------------------        private var _p:Point;        //--------------------------------------------------------------------------        //        //  properties        //        //--------------------------------------------------------------------------        public function get x():Number        {            return _p.x;        }        public function set x(value:Number):void        {            _p.x = value;        }        public function get y():Number        {            return _p.y;        }        public function set y(value:Number):void        {            _p.y = value;        }        public function get width():Number        {            return 0;        }        public function set width(value:Number):void        {        }        public function get height():Number        {            return 0;        }        public function set height(value:Number):void        {        }        //--------------------------------------------------------------------------        //        //  Methods: discription        //        //--------------------------------------------------------------------------        public function toString():String         {            return "Point2D[x=" + x + ",y=" + y + "]";        }
        public function clone():IGeom        {            return new Point2D(_p.x, _p.y);        }
        public function equals(__toCompare:IGeom):Boolean        {            var p:Point2D = __toCompare as Point2D;            return (p) ? _p.equals(new Point(p.x, p.y)) : false;        }
        public function containsPoint(point:Point2D, includeOnLine:Boolean = true):Boolean        {            includeOnLine;            return (point.x == _p.x && point.y == _p.y);        }
    }
}
